<RockSimDocument>
  <FileVersion>3</FileVersion>
  <DesignInformation>
    <RocketDesign>
      <Name>CLV-1</Name>
      <CalculateCD>1</CalculateCD>
      <FixedCd>0.75</FixedCd>
      <FixedCd2>0.8</FixedCd2>
      <FixedCd3>0.81</FixedCd3>
      <FixedCd2Alone>0.95</FixedCd2Alone>
      <FixedCd3Alone>0.95</FixedCd3Alone>
      <StageCount>1</StageCount>
      <Stage3Mass>4469.</Stage3Mass>
      <Stage2Mass>0.</Stage2Mass>
      <Stage1Mass>0.</Stage1Mass>
      <Stage321CG>0.</Stage321CG>
      <Stage32CG>0.</Stage32CG>
      <Stage3CG>1460.</Stage3CG>
      <Stage2CGAlone>0.</Stage2CGAlone>
      <Stage1CGAlone>0.</Stage1CGAlone>
      <CPCalcFlags>1</CPCalcFlags>
      <LaunchGuideLength>914.4</LaunchGuideLength>
      <UseKnownMass>0</UseKnownMass>
      <DefaultFinish>0</DefaultFinish>
      <FinishMedium>0</FinishMedium>
      <FinishCoatCount>1</FinishCoatCount>
      <GlueType>0</GlueType>
      <CPSimFlags>1</CPSimFlags>
      <LastSerialNumber>12</LastSerialNumber>
      <DisplayFlags>1</DisplayFlags>
      <MetricsFlags>0</MetricsFlags>
      <BarromanXN>0,2094.97,0,0</BarromanXN>
      <BarrowmanCNa>0,19.6539,0,0</BarrowmanCNa>
      <RockSimXN>0,2156.96,0,0</RockSimXN>
      <RockSimCNa>0,27.6535,0,0</RockSimCNa>
      <ViewType>0</ViewType>
      <ViewStageCount>1</ViewStageCount>
      <ViewTypeEdit>0</ViewTypeEdit>
      <ViewStageCountEdit>1</ViewStageCountEdit>
      <ZoomFactor>0.</ZoomFactor>
      <ZoomFactorEdit>0.</ZoomFactorEdit>
      <ScrollPosX>0</ScrollPosX>
      <ScrollPosY>0</ScrollPosY>
      <ScrollPosXEdit>0</ScrollPosXEdit>
      <ScrollPosYEdit>0</ScrollPosYEdit>
      <ThreeDFlags>0</ThreeDFlags>
      <ThreeDFlagsEdit>0</ThreeDFlagsEdit>
      <UseModelSprite>0</UseModelSprite>
      <StaticMarginRef>0</StaticMarginRef>
      <UserRefDiameter>0.</UserRefDiameter>
      <SideMarkerHeight>9.99998</SideMarkerHeight>
      <SideDimensionHeight>9.99998</SideDimensionHeight>
      <BaseMarkerHeight>9.99998</BaseMarkerHeight>
      <BaseDimensionHeight>9.99998</BaseDimensionHeight>
      <SimulationEventList>
        <SimulationEvent>
          <PartSerialNo>10</PartSerialNo>
          <Type>4</Type>
          <DeployAltitude>0.</DeployAltitude>
          <DeplyTime>0.</DeplyTime>
          <HasDeployed>0</HasDeployed>
          <DeployedAt_Altitude>0.</DeployedAt_Altitude>
          <DeployedAt_Velocity>0.</DeployedAt_Velocity>
          <DeployedAt_Range>0.</DeployedAt_Range>
          <DeployedAt_Time>0.</DeployedAt_Time>
          <DeviceID>-1</DeviceID>
        </SimulationEvent>
      </SimulationEventList>
      <Stage3Parts>
        <NoseCone>
          <PartMfg>Custom</PartMfg>
          <KnownMass>0.</KnownMass>
          <Density>128.148</Density>
          <Material>Fiberglass</Material>
          <Name>Nose cone</Name>
          <KnownCG>0.</KnownCG>
          <UseKnownCG>0</UseKnownCG>
          <Xb>0.</Xb>
          <CalcMass>25.5346</CalcMass>
          <CalcCG>321.4</CalcCG>
          <WettedSurface>0.0554355</WettedSurface>
          <PaintedSurface>0.0554355</PaintedSurface>
          <GlueJointLength>0.</GlueJointLength>
          <DensityType>0</DensityType>
          <RadialLoc>0.</RadialLoc>
          <RadialAngle>0.</RadialAngle>
          <Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
          <Opacity>1.</Opacity>
          <Specular>0.</Specular>
          <SpecularPower>1.</SpecularPower>
          <Ambient>0.</Ambient>
          <Diffuse>1.</Diffuse>
          <AbientColor>blue</AbientColor>
          <DiffuseColor>blue</DiffuseColor>
          <SpecularColor>white</SpecularColor>
          <UseSingleColor>1</UseSingleColor>
          <SerialNo>2</SerialNo>
          <DisplayFlags>0</DisplayFlags>
          <MetricsFlags>0</MetricsFlags>
          <LocationMode>0</LocationMode>
          <Color>blue</Color>
          <BarrowmanCNa>2.</BarrowmanCNa>
          <BarrowmanXN>0.31302</BarrowmanXN>
          <RockSimCNa>2.</RockSimCNa>
          <RockSimXN>0.31302</RockSimXN>
          <SimpleColorModel>1</SimpleColorModel>
          <ProduceTemplate>0</ProduceTemplate>
          <TemplateUnits>8</TemplateUnits>
          <Len>470.</Len>
          <BaseDia>75.</BaseDia>
          <FinishCode>0</FinishCode>
          <ShapeCode>0</ShapeCode>
          <ConstructionType>1</ConstructionType>
          <ShoulderLen>0.</ShoulderLen>
          <WallThickness>4.</WallThickness>
          <ShapeParameter>0.</ShapeParameter>
          <ShoulderOD>0.</ShoulderOD>
          <BaseExtensionLen>0.</BaseExtensionLen>
          <CoreDia>0.</CoreDia>
          <CoreLen>0.</CoreLen>
          <AttachedParts>
          </AttachedParts>
        </NoseCone>
        <BodyTube>
          <PartMfg>Public Missiles Ltd.</PartMfg>
          <KnownMass>0.</KnownMass>
          <Density>128.148</Density>
          <Material>Fiberglass</Material>
          <Name>Body tube</Name>
          <KnownCG>0.</KnownCG>
          <UseKnownCG>0</UseKnownCG>
          <Xb>0.</Xb>
          <CalcMass>61.0734</CalcMass>
          <CalcCG>1025.</CalcCG>
          <WettedSurface>0.48302</WettedSurface>
          <PaintedSurface>0.48302</PaintedSurface>
          <GlueJointLength>0.</GlueJointLength>
          <DensityType>0</DensityType>
          <RadialLoc>0.</RadialLoc>
          <RadialAngle>0.</RadialAngle>
          <Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
          <Opacity>1.</Opacity>
          <Specular>0.</Specular>
          <SpecularPower>1.</SpecularPower>
          <Ambient>0.</Ambient>
          <Diffuse>1.</Diffuse>
          <AbientColor>rgb(0,0,250)</AbientColor>
          <DiffuseColor>rgb(0,185,185)</DiffuseColor>
          <SpecularColor>rgb(255,255,255)</SpecularColor>
          <UseSingleColor>1</UseSingleColor>
          <SerialNo>1</SerialNo>
          <DisplayFlags>1</DisplayFlags>
          <MetricsFlags>0</MetricsFlags>
          <LocationMode>0</LocationMode>
          <Color>rgb(255,0,0)</Color>
          <BarrowmanCNa>0.</BarrowmanCNa>
          <BarrowmanXN>0.</BarrowmanXN>
          <RockSimCNa>0.</RockSimCNa>
          <RockSimXN>0.</RockSimXN>
          <SimpleColorModel>1</SimpleColorModel>
          <ProduceTemplate>0</ProduceTemplate>
          <TemplateUnits>8</TemplateUnits>
          <OD>75.0011</OD>
          <ID>72.9996</ID>
          <Len>2050.</Len>
          <FinishCode>0</FinishCode>
          <IsMotorMount>0</IsMotorMount>
          <MotorDia>0.</MotorDia>
          <EngineOverhang>0.5</EngineOverhang>
          <FrontExtension>0.</FrontExtension>
          <RearExtension>0.</RearExtension>
          <IsInsideTube>0</IsInsideTube>
          <AttachedParts>
            <FinSet>
              <PartMfg>Custom</PartMfg>
              <KnownMass>0.</KnownMass>
              <Density>128.148</Density>
              <Material>Fiberglass</Material>
              <Name>Fin set</Name>
              <KnownCG>0.</KnownCG>
              <UseKnownCG>0</UseKnownCG>
              <Xb>120.</Xb>
              <CalcMass>25.6328</CalcMass>
              <CalcCG>64.9999</CalcCG>
              <WettedSurface>0.028</WettedSurface>
              <PaintedSurface>0.084</PaintedSurface>
              <GlueJointLength>0.</GlueJointLength>
              <DensityType>0</DensityType>
              <RadialLoc>0.</RadialLoc>
              <RadialAngle>0.</RadialAngle>
              <Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
              <Opacity>1.</Opacity>
              <Specular>0.</Specular>
              <SpecularPower>1.</SpecularPower>
              <Ambient>0.</Ambient>
              <Diffuse>1.</Diffuse>
              <AbientColor>blue</AbientColor>
              <DiffuseColor>blue</DiffuseColor>
              <SpecularColor>white</SpecularColor>
              <UseSingleColor>1</UseSingleColor>
              <SerialNo>5</SerialNo>
              <DisplayFlags>0</DisplayFlags>
              <MetricsFlags>0</MetricsFlags>
              <LocationMode>2</LocationMode>
              <Color>blue</Color>
              <BarrowmanCNa>18.6171</BarrowmanCNa>
              <BarrowmanXN>2.30925</BarrowmanXN>
              <RockSimCNa>26.8809</RockSimCNa>
              <RockSimXN>2.30925</RockSimXN>
              <SimpleColorModel>0</SimpleColorModel>
              <ProduceTemplate>0</ProduceTemplate>
              <TemplateUnits>8</TemplateUnits>
              <FinCount>3</FinCount>
              <RootChord>130.</RootChord>
              <TipChord>69.9999</TipChord>
              <SemiSpan>140.</SemiSpan>
              <MidChordLen>140.</MidChordLen>
              <SweepDistance>29.9999</SweepDistance>
              <Thickness>4.7625</Thickness>
              <ShapeCode>0</ShapeCode>
              <FinishCode>0</FinishCode>
              <TipShapeCode>0</TipShapeCode>
              <TabLength>0.</TabLength>
              <TabDepth>0.</TabDepth>
              <TabOffset>0.</TabOffset>
              <SweepMode>1</SweepMode>
              <SweepAngle>0.209998</SweepAngle>
              <AttachedParts>
              </AttachedParts>
            </FinSet>
            <BodyTube>
              <PartMfg>Public Missiles Ltd.</PartMfg>
              <KnownMass>0.</KnownMass>
              <Density>128.148</Density>
              <Material>Fiberglass</Material>
              <Name>Body tube</Name>
              <KnownCG>0.</KnownCG>
              <UseKnownCG>0</UseKnownCG>
              <Xb>0.</Xb>
              <CalcMass>7.74509</CalcMass>
              <CalcCG>175.</CalcCG>
              <WettedSurface>0.</WettedSurface>
              <PaintedSurface>0.</PaintedSurface>
              <GlueJointLength>0.</GlueJointLength>
              <DensityType>0</DensityType>
              <RadialLoc>0.</RadialLoc>
              <RadialAngle>0.</RadialAngle>
              <Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
              <Opacity>1.</Opacity>
              <Specular>0.</Specular>
              <SpecularPower>1.</SpecularPower>
              <Ambient>0.</Ambient>
              <Diffuse>1.</Diffuse>
              <AbientColor>rgb(0,0,250)</AbientColor>
              <DiffuseColor>rgb(0,0,250)</DiffuseColor>
              <SpecularColor>rgb(255,255,255)</SpecularColor>
              <UseSingleColor>1</UseSingleColor>
              <SerialNo>9</SerialNo>
              <DisplayFlags>0</DisplayFlags>
              <MetricsFlags>0</MetricsFlags>
              <LocationMode>2</LocationMode>
              <Color>rgb(0,0,250)</Color>
              <BarrowmanCNa>0.</BarrowmanCNa>
              <BarrowmanXN>0.</BarrowmanXN>
              <RockSimCNa>0.</RockSimCNa>
              <RockSimXN>0.</RockSimXN>
              <SimpleColorModel>1</SimpleColorModel>
              <ProduceTemplate>0</ProduceTemplate>
              <TemplateUnits>8</TemplateUnits>
              <OD>55.9994</OD>
              <ID>54.0004</ID>
              <Len>349.999</Len>
              <FinishCode>0</FinishCode>
              <IsMotorMount>1</IsMotorMount>
              <MotorDia>54.</MotorDia>
              <EngineOverhang>12.7</EngineOverhang>
              <FrontExtension>0.</FrontExtension>
              <RearExtension>0.</RearExtension>
              <IsInsideTube>1</IsInsideTube>
              <AttachedParts>
              </AttachedParts>
            </BodyTube>
            <Parachute>
              <PartMfg>b2 Rocketry</PartMfg>
              <KnownMass>0.</KnownMass>
              <Density>0.00644188</Density>
              <Material>1.9 oz. Ripstop Nylon (SkyAngle)</Material>
              <Name>Parachute</Name>
              <KnownCG>0.</KnownCG>
              <UseKnownCG>0</UseKnownCG>
              <Xb>500.</Xb>
              <CalcMass>8.74583</CalcMass>
              <CalcCG>38.1</CalcCG>
              <WettedSurface>0.</WettedSurface>
              <PaintedSurface>0.</PaintedSurface>
              <GlueJointLength>0.</GlueJointLength>
              <DensityType>1</DensityType>
              <RadialLoc>0.</RadialLoc>
              <RadialAngle>0.</RadialAngle>
              <Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
              <Opacity>1.</Opacity>
              <Specular>0.</Specular>
              <SpecularPower>1.</SpecularPower>
              <Ambient>0.</Ambient>
              <Diffuse>1.</Diffuse>
              <AbientColor>blue</AbientColor>
              <DiffuseColor>blue</DiffuseColor>
              <SpecularColor>white</SpecularColor>
              <UseSingleColor>1</UseSingleColor>
              <SerialNo>10</SerialNo>
              <DisplayFlags>0</DisplayFlags>
              <MetricsFlags>0</MetricsFlags>
              <LocationMode>1</LocationMode>
              <Color>blue</Color>
              <BarrowmanCNa>0.</BarrowmanCNa>
              <BarrowmanXN>0.</BarrowmanXN>
              <RockSimCNa>0.</RockSimCNa>
              <RockSimXN>0.</RockSimXN>
              <SimpleColorModel>1</SimpleColorModel>
              <ProduceTemplate>0</ProduceTemplate>
              <TemplateUnits>8</TemplateUnits>
              <Dia>457.2</Dia>
              <SpillHoleDia>0.</SpillHoleDia>
              <SideCount>6</SideCount>
              <ShroudLineCount>6</ShroudLineCount>
              <Thickness>0.</Thickness>
              <ShroudLineLen>0.</ShroudLineLen>
              <ChuteCount>1</ChuteCount>
              <ShroudLineMassPerMM>0.00033</ShroudLineMassPerMM>
              <ShroudLineMaterial>70 Lb. kevlar</ShroudLineMaterial>
              <DragCoefficient>0.75</DragCoefficient>
              <AttachedParts>
              </AttachedParts>
            </Parachute>
          </AttachedParts>
        </BodyTube>
        <Transition>
          <PartMfg>Custom</PartMfg>
          <KnownMass>0.</KnownMass>
          <Density>128.148</Density>
          <Material>Fiberglass</Material>
          <Name>Transition</Name>
          <KnownCG>0.</KnownCG>
          <UseKnownCG>0</UseKnownCG>
          <Xb>0.</Xb>
          <CalcMass>14.7956</CalcMass>
          <CalcCG>15.6313</CalcCG>
          <WettedSurface>0.00740474</WettedSurface>
          <PaintedSurface>0.00740474</PaintedSurface>
          <GlueJointLength>0.</GlueJointLength>
          <DensityType>0</DensityType>
          <RadialLoc>0.</RadialLoc>
          <RadialAngle>0.</RadialAngle>
          <Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
          <Opacity>1.</Opacity>
          <Specular>0.</Specular>
          <SpecularPower>1.</SpecularPower>
          <Ambient>0.</Ambient>
          <Diffuse>1.</Diffuse>
          <AbientColor>blue</AbientColor>
          <DiffuseColor>blue</DiffuseColor>
          <SpecularColor>white</SpecularColor>
          <UseSingleColor>1</UseSingleColor>
          <SerialNo>3</SerialNo>
          <DisplayFlags>0</DisplayFlags>
          <MetricsFlags>0</MetricsFlags>
          <LocationMode>0</LocationMode>
          <Color>blue</Color>
          <BarrowmanCNa>-0.96326</BarrowmanCNa>
          <BarrowmanXN>2.53655</BarrowmanXN>
          <RockSimCNa>-0.96326</RockSimCNa>
          <RockSimXN>2.53655</RockSimXN>
          <SimpleColorModel>1</SimpleColorModel>
          <ProduceTemplate>0</ProduceTemplate>
          <TemplateUnits>8</TemplateUnits>
          <FrontDia>75.0011</FrontDia>
          <RearDia>54.</RearDia>
          <Len>35.0012</Len>
          <FinishCode>0</FinishCode>
          <FrontShoulderLen>0.</FrontShoulderLen>
          <RearShoulderLen>0.</RearShoulderLen>
          <ConstructionType>0</ConstructionType>
          <WallThickness>0.</WallThickness>
          <FrontShoulderDia>0.</FrontShoulderDia>
          <RearShoulderDia>0.</RearShoulderDia>
          <CoreDia>0.</CoreDia>
          <ShapeCode>0</ShapeCode>
          <ShapeParameter>0.</ShapeParameter>
          <EquivNoseLen>124.999</EquivNoseLen>
          <EquivNoseOffset>89.9982</EquivNoseOffset>
          <AttachedParts>
          </AttachedParts>
        </Transition>
      </Stage3Parts>
      <Stage2Parts>
      </Stage2Parts>
      <Stage1Parts>
      </Stage1Parts>
      <SideViewDims>
      </SideViewDims>
      <BaseViewDims>
      </BaseViewDims>
      <VertViewDims>
      </VertViewDims>
    </RocketDesign>
  </DesignInformation>
  <SimulationResultsList>
    <SimulationResults>
      <MaxAltitude>772.941</MaxAltitude>
      <MaxVelocity>130.687</MaxVelocity>
      <MaxAcceleration>130.951</MaxAcceleration>
      <TimeToApogee>12.615</TimeToApogee>
      <OptimalDelay>11.4338</OptimalDelay>
      <MultiDelayCount>0</MultiDelayCount>
      <FinalState>2</FinalState>
      <TimeToBurnout>1.18125</TimeToBurnout>
      <TimeToLanding>44.9862</TimeToLanding>
      <TimeToEject>0.</TimeToEject>
      <MinLaunchGuideLen>0.727851</MinLaunchGuideLen>
      <MaxVertVelocity>129.604</MaxVertVelocity>
      <MaxHorzVelocity>6.75891</MaxHorzVelocity>
      <MaxVertAcceleration>130.189</MaxVertAcceleration>
      <MaxHorzAcceleration>0.64314</MaxHorzAcceleration>
      <MaxRange>136.427</MaxRange>
      <LaunchStartVelocity>0.</LaunchStartVelocity>
      <LaunchStartAltitude>0.</LaunchStartAltitude>
      <LaunchGuideLen>2000.</LaunchGuideLen>
      <LaunchWindDirection>0</LaunchWindDirection>
      <LaunchWindSpeed>0.</LaunchWindSpeed>
      <LaunchDirection>0</LaunchDirection>
      <LaunchAngle>0.</LaunchAngle>
      <LaunchBarometer>760.</LaunchBarometer>
      <LaunchLatitude>1.571</LaunchLatitude>
      <LaunchHumidity>50.</LaunchHumidity>
      <LaunchTemperature>15.</LaunchTemperature>
      <LaunchAltitude>0.</LaunchAltitude>
      <CompStateMask>0</CompStateMask>
      <LaunchWindPreset>5</LaunchWindPreset>
      <LaunchWindLowSpeed>6.7056</LaunchWindLowSpeed>
      <LaunchWindHighSpeed>11.176</LaunchWindHighSpeed>
      <LaunchWindTurbulencePreset>2</LaunchWindTurbulencePreset>
      <LaunchWindFrequency>0.01</LaunchWindFrequency>
      <LaunchWindDeltaFrequency>0.02</LaunchWindDeltaFrequency>
      <LaunchUseRandomConditions>0</LaunchUseRandomConditions>
      <LaunchCloudCoverPreset>5</LaunchCloudCoverPreset>
      <LaunchCCLow>0.</LaunchCCLow>
      <LaunchCCHigh>0.1</LaunchCCHigh>
      <LaunchThermalPosPreset>1</LaunchThermalPosPreset>
      <LaunchThermalPos>0.</LaunchThermalPos>
      <LaunchMultipleThermals>0</LaunchMultipleThermals>
      <LaunchMaxThermals>3</LaunchMaxThermals>
      <LaunchThermalDia>300.</LaunchThermalDia>
      <LaunchThermalHeight>2000.</LaunchThermalHeight>
      <LaunchThermalSpeedPreset>1</LaunchThermalSpeedPreset>
      <LaunchThermalSpeed>5.99999</LaunchThermalSpeed>
      <LaunchLossPreset>2</LaunchLossPreset>
      <LaunchLossPercent>0.99</LaunchLossPercent>
      <LaunchSiteDia>2000.</LaunchSiteDia>
      <LaunchDriftRangeToLoss>1500.</LaunchDriftRangeToLoss>
      <LaunchPayloadDamagePreset>2</LaunchPayloadDamagePreset>
      <LaunchPayloadDamagePercent>0.98</LaunchPayloadDamagePercent>
      <LaunchEngineMisfirePreset>1</LaunchEngineMisfirePreset>
      <LaunchEngineMisfirePercent>0.</LaunchEngineMisfirePercent>
      <LaunchVariableIgnitionDelay>0</LaunchVariableIgnitionDelay>
      <LaunchVariableIgnitionDelaySec>0.08</LaunchVariableIgnitionDelaySec>
      <LaunchRecDeviceFailurePreset>1</LaunchRecDeviceFailurePreset>
      <LaunchRecDeviceFailurePercent>0.</LaunchRecDeviceFailurePercent>
      <LaunchAriframeFailurePreset>1</LaunchAriframeFailurePreset>
      <LaunchAirframeFailurePercent>0.</LaunchAirframeFailurePercent>
      <LaunchTrackLossPreset>1</LaunchTrackLossPreset>
      <LaunchTeckLossPercent>0.</LaunchTeckLossPercent>
      <SimulationName>[I540WT-None] </SimulationName>
      <VelocityAtLaunchGuideEnd>22.4816</VelocityAtLaunchGuideEnd>
      <WindStartAltitude>0.</WindStartAltitude>
      <TimeToWindShear>0.</TimeToWindShear>
      <TimeToFreeFlight>0.195</TimeToFreeFlight>
      <TimeToMaxVelocity>1.1375</TimeToMaxVelocity>
      <TimeToMaxAcceleration>0.48</TimeToMaxAcceleration>
      <SamplesPerSecond>800.</SamplesPerSecond>
      <SimulationType>1</SimulationType>
      <LocationDataServerName>Earth</LocationDataServerName>
      <LocationDataServerDisplayName>Standard earth condistions.</LocationDataServerDisplayName>
      <ExecutionTime>0.51</ExecutionTime>
      <RangeAtLanding>81.0742</RangeAtLanding>
      <VelocityAtLanding>28.0441</VelocityAtLanding>
      <XVelcoityAtLanding>6.71788</XVelcoityAtLanding>
      <YVelocityAtLanding>-27.2276</YVelocityAtLanding>
      <StageSeparationTime>0,0,0</StageSeparationTime>
      <StageEjectTime>-1,-1,-1</StageEjectTime>
      <TimeToDeployment>0,0,12.615</TimeToDeployment>
      <DeploymentType>32,32,80</DeploymentType>
      <SamplesPerSecondDescent>1.</SamplesPerSecondDescent>
      <CalculationFlags>1</CalculationFlags>
      <Mass0>4.5512</Mass0>
      <CG0>0.308774</CG0>
      <LaterialMOI0>3.02665</LaterialMOI0>
      <RadialMOI0>0.00527951</RadialMOI0>
      <SimulationEvents>
        <SimulationEvent>
          <PartSerialNo>10</PartSerialNo>
          <Type>4</Type>
          <DeployAltitude>0.</DeployAltitude>
          <DeplyTime>0.</DeplyTime>
          <HasDeployed>1</HasDeployed>
          <DeployedAt_Altitude>772.941</DeployedAt_Altitude>
          <DeployedAt_Velocity>13.4722</DeployedAt_Velocity>
          <DeployedAt_Range>-136.427</DeployedAt_Range>
          <DeployedAt_Time>12.615</DeployedAt_Time>
          <DeviceID>128</DeviceID>
        </SimulationEvent>
      </SimulationEvents>
      <Stage1Engines>
      </Stage1Engines>
      <Stage2Engines>
      </Stage2Engines>
      <Stage3Engines>
        <EngineSet>
          <EngineCount>1</EngineCount>
          <EngineCode>I540WT</EngineCode>
          <IgnitionDelay>0.</IgnitionDelay>
          <EngineMfg>Cesaroni</EngineMfg>
          <EngineOverhang>12.7</EngineOverhang>
          <CasingCG>0.</CasingCG>
          <MountSerialNo>9</MountSerialNo>
          <EjectionDelay>-2.</EjectionDelay>
        </EngineSet>
      </Stage3Engines>
    </SimulationResults>
    <SimulationResults>
      <MaxAltitude>1074.75</MaxAltitude>
      <MaxVelocity>156.375</MaxVelocity>
      <MaxAcceleration>123.326</MaxAcceleration>
      <TimeToApogee>14.7775</TimeToApogee>
      <OptimalDelay>12.6463</OptimalDelay>
      <MultiDelayCount>0</MultiDelayCount>
      <FinalState>2</FinalState>
      <TimeToBurnout>2.13125</TimeToBurnout>
      <TimeToLanding>56.765</TimeToLanding>
      <TimeToEject>0.</TimeToEject>
      <MinLaunchGuideLen>0.750832</MinLaunchGuideLen>
      <MaxVertVelocity>151.654</MaxVertVelocity>
      <MaxHorzVelocity>11.176</MaxHorzVelocity>
      <MaxVertAcceleration>123.326</MaxVertAcceleration>
      <MaxHorzAcceleration>1.65502</MaxHorzAcceleration>
      <MaxRange>360.852</MaxRange>
      <LaunchStartVelocity>0.</LaunchStartVelocity>
      <LaunchStartAltitude>0.</LaunchStartAltitude>
      <LaunchGuideLen>2000.</LaunchGuideLen>
      <LaunchWindDirection>0</LaunchWindDirection>
      <LaunchWindSpeed>0.</LaunchWindSpeed>
      <LaunchDirection>0</LaunchDirection>
      <LaunchAngle>0.</LaunchAngle>
      <LaunchBarometer>760.</LaunchBarometer>
      <LaunchLatitude>1.571</LaunchLatitude>
      <LaunchHumidity>50.</LaunchHumidity>
      <LaunchTemperature>15.</LaunchTemperature>
      <LaunchAltitude>0.</LaunchAltitude>
      <CompStateMask>0</CompStateMask>
      <LaunchWindPreset>5</LaunchWindPreset>
      <LaunchWindLowSpeed>6.7056</LaunchWindLowSpeed>
      <LaunchWindHighSpeed>11.176</LaunchWindHighSpeed>
      <LaunchWindTurbulencePreset>2</LaunchWindTurbulencePreset>
      <LaunchWindFrequency>0.01</LaunchWindFrequency>
      <LaunchWindDeltaFrequency>0.02</LaunchWindDeltaFrequency>
      <LaunchUseRandomConditions>0</LaunchUseRandomConditions>
      <LaunchCloudCoverPreset>5</LaunchCloudCoverPreset>
      <LaunchCCLow>0.</LaunchCCLow>
      <LaunchCCHigh>0.1</LaunchCCHigh>
      <LaunchThermalPosPreset>1</LaunchThermalPosPreset>
      <LaunchThermalPos>0.</LaunchThermalPos>
      <LaunchMultipleThermals>0</LaunchMultipleThermals>
      <LaunchMaxThermals>3</LaunchMaxThermals>
      <LaunchThermalDia>300.</LaunchThermalDia>
      <LaunchThermalHeight>2000.</LaunchThermalHeight>
      <LaunchThermalSpeedPreset>1</LaunchThermalSpeedPreset>
      <LaunchThermalSpeed>5.99999</LaunchThermalSpeed>
      <LaunchLossPreset>2</LaunchLossPreset>
      <LaunchLossPercent>0.99</LaunchLossPercent>
      <LaunchSiteDia>2000.</LaunchSiteDia>
      <LaunchDriftRangeToLoss>1500.</LaunchDriftRangeToLoss>
      <LaunchPayloadDamagePreset>2</LaunchPayloadDamagePreset>
      <LaunchPayloadDamagePercent>0.98</LaunchPayloadDamagePercent>
      <LaunchEngineMisfirePreset>1</LaunchEngineMisfirePreset>
      <LaunchEngineMisfirePercent>0.</LaunchEngineMisfirePercent>
      <LaunchVariableIgnitionDelay>0</LaunchVariableIgnitionDelay>
      <LaunchVariableIgnitionDelaySec>0.08</LaunchVariableIgnitionDelaySec>
      <LaunchRecDeviceFailurePreset>1</LaunchRecDeviceFailurePreset>
      <LaunchRecDeviceFailurePercent>0.</LaunchRecDeviceFailurePercent>
      <LaunchAriframeFailurePreset>1</LaunchAriframeFailurePreset>
      <LaunchAirframeFailurePercent>0.</LaunchAirframeFailurePercent>
      <LaunchTrackLossPreset>1</LaunchTrackLossPreset>
      <LaunchTeckLossPercent>0.</LaunchTeckLossPercent>
      <SimulationName>[J360-None] </SimulationName>
      <VelocityAtLaunchGuideEnd>21.9166</VelocityAtLaunchGuideEnd>
      <WindStartAltitude>0.</WindStartAltitude>
      <TimeToWindShear>0.</TimeToWindShear>
      <TimeToFreeFlight>0.2025</TimeToFreeFlight>
      <TimeToMaxVelocity>1.81625</TimeToMaxVelocity>
      <TimeToMaxAcceleration>0.12375</TimeToMaxAcceleration>
      <SamplesPerSecond>800.</SamplesPerSecond>
      <SimulationType>1</SimulationType>
      <LocationDataServerName>Earth</LocationDataServerName>
      <LocationDataServerDisplayName>Standard earth condistions.</LocationDataServerDisplayName>
      <ExecutionTime>0.531</ExecutionTime>
      <RangeAtLanding>107.712</RangeAtLanding>
      <VelocityAtLanding>29.8229</VelocityAtLanding>
      <XVelcoityAtLanding>11.1296</XVelcoityAtLanding>
      <YVelocityAtLanding>-27.6683</YVelocityAtLanding>
      <StageSeparationTime>0,0,0</StageSeparationTime>
      <StageEjectTime>-1,-1,-1</StageEjectTime>
      <TimeToDeployment>0,0,14.7775</TimeToDeployment>
      <DeploymentType>32,32,80</DeploymentType>
      <SamplesPerSecondDescent>1.</SamplesPerSecondDescent>
      <CalculationFlags>1</CalculationFlags>
      <Mass0>4.66218</Mass0>
      <CG0>0.353392</CG0>
      <LaterialMOI0>3.26613</LaterialMOI0>
      <RadialMOI0>0.00804496</RadialMOI0>
      <SimulationEvents>
        <SimulationEvent>
          <PartSerialNo>10</PartSerialNo>
          <Type>4</Type>
          <DeployAltitude>0.</DeployAltitude>
          <DeplyTime>0.</DeplyTime>
          <HasDeployed>1</HasDeployed>
          <DeployedAt_Altitude>1074.75</DeployedAt_Altitude>
          <DeployedAt_Velocity>28.7296</DeployedAt_Velocity>
          <DeployedAt_Range>-360.852</DeployedAt_Range>
          <DeployedAt_Time>14.7775</DeployedAt_Time>
          <DeviceID>128</DeviceID>
        </SimulationEvent>
      </SimulationEvents>
      <Stage1Engines>
      </Stage1Engines>
      <Stage2Engines>
      </Stage2Engines>
      <Stage3Engines>
        <EngineSet>
          <EngineCount>1</EngineCount>
          <EngineCode>J360</EngineCode>
          <IgnitionDelay>0.</IgnitionDelay>
          <EngineMfg>Cesaroni</EngineMfg>
          <EngineOverhang>12.7</EngineOverhang>
          <CasingCG>0.</CasingCG>
          <MountSerialNo>9</MountSerialNo>
          <EjectionDelay>-2.</EjectionDelay>
        </EngineSet>
      </Stage3Engines>
    </SimulationResults>
    <SimulationResults>
      <MaxAltitude>2420.92</MaxAltitude>
      <MaxVelocity>238.205</MaxVelocity>
      <MaxAcceleration>107.6</MaxAcceleration>
      <TimeToApogee>22.2187</TimeToApogee>
      <OptimalDelay>18.3187</OptimalDelay>
      <MultiDelayCount>0</MultiDelayCount>
      <FinalState>2</FinalState>
      <TimeToBurnout>3.9</TimeToBurnout>
      <TimeToLanding>95.5662</TimeToLanding>
      <TimeToEject>0.</TimeToEject>
      <MinLaunchGuideLen>0.923371</MinLaunchGuideLen>
      <MaxVertVelocity>230.609</MaxVertVelocity>
      <MaxHorzVelocity>10.8345</MaxHorzVelocity>
      <MaxVertAcceleration>107.6</MaxVertAcceleration>
      <MaxHorzAcceleration>2.27829</MaxHorzAcceleration>
      <MaxRange>907.744</MaxRange>
      <LaunchStartVelocity>0.</LaunchStartVelocity>
      <LaunchStartAltitude>0.</LaunchStartAltitude>
      <LaunchGuideLen>2000.</LaunchGuideLen>
      <LaunchWindDirection>0</LaunchWindDirection>
      <LaunchWindSpeed>0.</LaunchWindSpeed>
      <LaunchDirection>0</LaunchDirection>
      <LaunchAngle>0.</LaunchAngle>
      <LaunchBarometer>760.</LaunchBarometer>
      <LaunchLatitude>1.571</LaunchLatitude>
      <LaunchHumidity>50.</LaunchHumidity>
      <LaunchTemperature>15.</LaunchTemperature>
      <LaunchAltitude>0.</LaunchAltitude>
      <CompStateMask>0</CompStateMask>
      <LaunchWindPreset>5</LaunchWindPreset>
      <LaunchWindLowSpeed>6.7056</LaunchWindLowSpeed>
      <LaunchWindHighSpeed>11.176</LaunchWindHighSpeed>
      <LaunchWindTurbulencePreset>2</LaunchWindTurbulencePreset>
      <LaunchWindFrequency>0.01</LaunchWindFrequency>
      <LaunchWindDeltaFrequency>0.02</LaunchWindDeltaFrequency>
      <LaunchUseRandomConditions>0</LaunchUseRandomConditions>
      <LaunchCloudCoverPreset>5</LaunchCloudCoverPreset>
      <LaunchCCLow>0.</LaunchCCLow>
      <LaunchCCHigh>0.1</LaunchCCHigh>
      <LaunchThermalPosPreset>1</LaunchThermalPosPreset>
      <LaunchThermalPos>0.</LaunchThermalPos>
      <LaunchMultipleThermals>0</LaunchMultipleThermals>
      <LaunchMaxThermals>3</LaunchMaxThermals>
      <LaunchThermalDia>300.</LaunchThermalDia>
      <LaunchThermalHeight>2000.</LaunchThermalHeight>
      <LaunchThermalSpeedPreset>1</LaunchThermalSpeedPreset>
      <LaunchThermalSpeed>5.99999</LaunchThermalSpeed>
      <LaunchLossPreset>2</LaunchLossPreset>
      <LaunchLossPercent>0.99</LaunchLossPercent>
      <LaunchSiteDia>2000.</LaunchSiteDia>
      <LaunchDriftRangeToLoss>1500.</LaunchDriftRangeToLoss>
      <LaunchPayloadDamagePreset>2</LaunchPayloadDamagePreset>
      <LaunchPayloadDamagePercent>0.98</LaunchPayloadDamagePercent>
      <LaunchEngineMisfirePreset>1</LaunchEngineMisfirePreset>
      <LaunchEngineMisfirePercent>0.</LaunchEngineMisfirePercent>
      <LaunchVariableIgnitionDelay>0</LaunchVariableIgnitionDelay>
      <LaunchVariableIgnitionDelaySec>0.08</LaunchVariableIgnitionDelaySec>
      <LaunchRecDeviceFailurePreset>1</LaunchRecDeviceFailurePreset>
      <LaunchRecDeviceFailurePercent>0.</LaunchRecDeviceFailurePercent>
      <LaunchAriframeFailurePreset>1</LaunchAriframeFailurePreset>
      <LaunchAirframeFailurePercent>0.</LaunchAirframeFailurePercent>
      <LaunchTrackLossPreset>1</LaunchTrackLossPreset>
      <LaunchTeckLossPercent>0.</LaunchTeckLossPercent>
      <SimulationName>[K570-None] </SimulationName>
      <VelocityAtLaunchGuideEnd>20.1359</VelocityAtLaunchGuideEnd>
      <WindStartAltitude>0.</WindStartAltitude>
      <TimeToWindShear>0.</TimeToWindShear>
      <TimeToFreeFlight>0.225</TimeToFreeFlight>
      <TimeToMaxVelocity>3.36125</TimeToMaxVelocity>
      <TimeToMaxAcceleration>0.05</TimeToMaxAcceleration>
      <SamplesPerSecond>800.</SamplesPerSecond>
      <SimulationType>1</SimulationType>
      <LocationDataServerName>Earth</LocationDataServerName>
      <LocationDataServerDisplayName>Standard earth condistions.</LocationDataServerDisplayName>
      <ExecutionTime>1.765</ExecutionTime>
      <RangeAtLanding>-155.722</RangeAtLanding>
      <VelocityAtLanding>34.3295</VelocityAtLanding>
      <XVelcoityAtLanding>10.8345</XVelcoityAtLanding>
      <YVelocityAtLanding>-32.5749</YVelocityAtLanding>
      <StageSeparationTime>0,0,0</StageSeparationTime>
      <StageEjectTime>-1,-1,1.6e+308</StageEjectTime>
      <TimeToDeployment>0,0,22.2187</TimeToDeployment>
      <DeploymentType>32,32,80</DeploymentType>
      <SamplesPerSecondDescent>1.</SamplesPerSecondDescent>
      <CalculationFlags>1</CalculationFlags>
      <Mass0>7.685</Mass0>
      <CG0>1.6417</CG0>
      <LaterialMOI0>0.864167</LaterialMOI0>
      <RadialMOI0>0.0257067</RadialMOI0>
      <SimulationEvents>
        <SimulationEvent>
          <PartSerialNo>10</PartSerialNo>
          <Type>4</Type>
          <DeployAltitude>0.</DeployAltitude>
          <DeplyTime>0.</DeplyTime>
          <HasDeployed>1</HasDeployed>
          <DeployedAt_Altitude>2420.92</DeployedAt_Altitude>
          <DeployedAt_Velocity>42.1362</DeployedAt_Velocity>
          <DeployedAt_Range>-907.744</DeployedAt_Range>
          <DeployedAt_Time>22.2187</DeployedAt_Time>
          <DeviceID>128</DeviceID>
        </SimulationEvent>
      </SimulationEvents>
      <Stage1Engines>
      </Stage1Engines>
      <Stage2Engines>
      </Stage2Engines>
      <Stage3Engines>
        <EngineSet>
          <EngineCount>1</EngineCount>
          <EngineCode>K570</EngineCode>
          <IgnitionDelay>0.</IgnitionDelay>
          <EngineMfg>Cesaroni</EngineMfg>
          <EngineOverhang>12.7</EngineOverhang>
          <CasingCG>0.</CasingCG>
          <MountSerialNo>9</MountSerialNo>
          <EjectionDelay>-2.</EjectionDelay>
        </EngineSet>
      </Stage3Engines>
    </SimulationResults>
    <SimulationResults>
      <MaxAltitude>2559.58</MaxAltitude>
      <MaxVelocity>267.904</MaxVelocity>
      <MaxAcceleration>114.69</MaxAcceleration>
      <TimeToApogee>22.065</TimeToApogee>
      <OptimalDelay>18.015</OptimalDelay>
      <MultiDelayCount>0</MultiDelayCount>
      <FinalState>2</FinalState>
      <TimeToBurnout>4.05</TimeToBurnout>
      <TimeToLanding>114.254</TimeToLanding>
      <TimeToEject>0.</TimeToEject>
      <MinLaunchGuideLen>0.86951</MinLaunchGuideLen>
      <MaxVertVelocity>258.736</MaxVertVelocity>
      <MaxHorzVelocity>11.176</MaxHorzVelocity>
      <MaxVertAcceleration>114.69</MaxVertAcceleration>
      <MaxHorzAcceleration>4.14223</MaxHorzAcceleration>
      <MaxRange>919.375</MaxRange>
      <LaunchStartVelocity>0.</LaunchStartVelocity>
      <LaunchStartAltitude>0.</LaunchStartAltitude>
      <LaunchGuideLen>2000.</LaunchGuideLen>
      <LaunchWindDirection>0</LaunchWindDirection>
      <LaunchWindSpeed>0.</LaunchWindSpeed>
      <LaunchDirection>0</LaunchDirection>
      <LaunchAngle>0.</LaunchAngle>
      <LaunchBarometer>760.</LaunchBarometer>
      <LaunchLatitude>1.571</LaunchLatitude>
      <LaunchHumidity>50.</LaunchHumidity>
      <LaunchTemperature>15.</LaunchTemperature>
      <LaunchAltitude>0.</LaunchAltitude>
      <CompStateMask>0</CompStateMask>
      <LaunchWindPreset>5</LaunchWindPreset>
      <LaunchWindLowSpeed>6.7056</LaunchWindLowSpeed>
      <LaunchWindHighSpeed>11.176</LaunchWindHighSpeed>
      <LaunchWindTurbulencePreset>2</LaunchWindTurbulencePreset>
      <LaunchWindFrequency>0.01</LaunchWindFrequency>
      <LaunchWindDeltaFrequency>0.02</LaunchWindDeltaFrequency>
      <LaunchUseRandomConditions>0</LaunchUseRandomConditions>
      <LaunchCloudCoverPreset>5</LaunchCloudCoverPreset>
      <LaunchCCLow>0.</LaunchCCLow>
      <LaunchCCHigh>0.1</LaunchCCHigh>
      <LaunchThermalPosPreset>1</LaunchThermalPosPreset>
      <LaunchThermalPos>0.</LaunchThermalPos>
      <LaunchMultipleThermals>0</LaunchMultipleThermals>
      <LaunchMaxThermals>3</LaunchMaxThermals>
      <LaunchThermalDia>300.</LaunchThermalDia>
      <LaunchThermalHeight>2000.</LaunchThermalHeight>
      <LaunchThermalSpeedPreset>1</LaunchThermalSpeedPreset>
      <LaunchThermalSpeed>5.99999</LaunchThermalSpeed>
      <LaunchLossPreset>2</LaunchLossPreset>
      <LaunchLossPercent>0.99</LaunchLossPercent>
      <LaunchSiteDia>2000.</LaunchSiteDia>
      <LaunchDriftRangeToLoss>1500.</LaunchDriftRangeToLoss>
      <LaunchPayloadDamagePreset>2</LaunchPayloadDamagePreset>
      <LaunchPayloadDamagePercent>0.98</LaunchPayloadDamagePercent>
      <LaunchEngineMisfirePreset>1</LaunchEngineMisfirePreset>
      <LaunchEngineMisfirePercent>0.</LaunchEngineMisfirePercent>
      <LaunchVariableIgnitionDelay>0</LaunchVariableIgnitionDelay>
      <LaunchVariableIgnitionDelaySec>0.08</LaunchVariableIgnitionDelaySec>
      <LaunchRecDeviceFailurePreset>1</LaunchRecDeviceFailurePreset>
      <LaunchRecDeviceFailurePercent>0.</LaunchRecDeviceFailurePercent>
      <LaunchAriframeFailurePreset>1</LaunchAriframeFailurePreset>
      <LaunchAirframeFailurePercent>0.</LaunchAirframeFailurePercent>
      <LaunchTrackLossPreset>1</LaunchTrackLossPreset>
      <LaunchTeckLossPercent>0.</LaunchTeckLossPercent>
      <SimulationName>[K445-None] </SimulationName>
      <VelocityAtLaunchGuideEnd>20.7173</VelocityAtLaunchGuideEnd>
      <WindStartAltitude>0.</WindStartAltitude>
      <TimeToWindShear>0.</TimeToWindShear>
      <TimeToFreeFlight>0.21875</TimeToFreeFlight>
      <TimeToMaxVelocity>3.3925</TimeToMaxVelocity>
      <TimeToMaxAcceleration>0.05</TimeToMaxAcceleration>
      <SamplesPerSecond>800.</SamplesPerSecond>
      <SimulationType>1</SimulationType>
      <LocationDataServerName>Earth</LocationDataServerName>
      <LocationDataServerDisplayName>Standard earth condistions.</LocationDataServerDisplayName>
      <ExecutionTime>1.503</ExecutionTime>
      <RangeAtLanding>92.6274</RangeAtLanding>
      <VelocityAtLanding>28.9632</VelocityAtLanding>
      <XVelcoityAtLanding>11.1584</XVelcoityAtLanding>
      <YVelocityAtLanding>-26.7274</YVelocityAtLanding>
      <StageSeparationTime>0,0,0</StageSeparationTime>
      <StageEjectTime>-1,-1,-1</StageEjectTime>
      <TimeToDeployment>0,0,22.065</TimeToDeployment>
      <DeploymentType>32,32,80</DeploymentType>
      <SamplesPerSecondDescent>1.</SamplesPerSecondDescent>
      <CalculationFlags>1</CalculationFlags>
      <Mass0>5.351</Mass0>
      <CG0>0.608918</CG0>
      <LaterialMOI0>4.54013</LaterialMOI0>
      <RadialMOI0>0.0147939</RadialMOI0>
      <SimulationEvents>
        <SimulationEvent>
          <PartSerialNo>10</PartSerialNo>
          <Type>4</Type>
          <DeployAltitude>0.</DeployAltitude>
          <DeplyTime>0.</DeplyTime>
          <HasDeployed>1</HasDeployed>
          <DeployedAt_Altitude>2559.58</DeployedAt_Altitude>
          <DeployedAt_Velocity>41.0014</DeployedAt_Velocity>
          <DeployedAt_Range>-919.375</DeployedAt_Range>
          <DeployedAt_Time>22.065</DeployedAt_Time>
          <DeviceID>128</DeviceID>
        </SimulationEvent>
      </SimulationEvents>
      <Stage1Engines>
      </Stage1Engines>
      <Stage2Engines>
      </Stage2Engines>
      <Stage3Engines>
        <EngineSet>
          <EngineCount>1</EngineCount>
          <EngineCode>K445</EngineCode>
          <IgnitionDelay>0.</IgnitionDelay>
          <EngineMfg>Cesaroni</EngineMfg>
          <EngineOverhang>12.7</EngineOverhang>
          <CasingCG>0.</CasingCG>
          <MountSerialNo>9</MountSerialNo>
          <EjectionDelay>-2.</EjectionDelay>
        </EngineSet>
      </Stage3Engines>
    </SimulationResults>
    <SimulationResults>
      <MaxAltitude>1771.07</MaxAltitude>
      <MaxVelocity>188.691</MaxVelocity>
      <MaxAcceleration>80.211</MaxAcceleration>
      <TimeToApogee>19.6163</TimeToApogee>
      <OptimalDelay>15.5663</OptimalDelay>
      <MultiDelayCount>0</MultiDelayCount>
      <FinalState>2</FinalState>
      <TimeToBurnout>4.05</TimeToBurnout>
      <TimeToLanding>74.745</TimeToLanding>
      <TimeToEject>0.</TimeToEject>
      <MinLaunchGuideLen>1.22513</MinLaunchGuideLen>
      <MaxVertVelocity>185.755</MaxVertVelocity>
      <MaxHorzVelocity>4.47041</MaxHorzVelocity>
      <MaxVertAcceleration>80.211</MaxVertAcceleration>
      <MaxHorzAcceleration>1.04732</MaxHorzAcceleration>
      <MaxRange>485.277</MaxRange>
      <LaunchStartVelocity>0.</LaunchStartVelocity>
      <LaunchStartAltitude>0.</LaunchStartAltitude>
      <LaunchGuideLen>914.4</LaunchGuideLen>
      <LaunchWindDirection>0</LaunchWindDirection>
      <LaunchWindSpeed>0.</LaunchWindSpeed>
      <LaunchDirection>0</LaunchDirection>
      <LaunchAngle>0.</LaunchAngle>
      <LaunchBarometer>759.813</LaunchBarometer>
      <LaunchLatitude>1.571</LaunchLatitude>
      <LaunchHumidity>50.</LaunchHumidity>
      <LaunchTemperature>15.</LaunchTemperature>
      <LaunchAltitude>0.</LaunchAltitude>
      <CompStateMask>0</CompStateMask>
      <LaunchWindPreset>99</LaunchWindPreset>
      <LaunchWindLowSpeed>4.47041</LaunchWindLowSpeed>
      <LaunchWindHighSpeed>4.47041</LaunchWindHighSpeed>
      <LaunchWindTurbulencePreset>1</LaunchWindTurbulencePreset>
      <LaunchWindFrequency>0.</LaunchWindFrequency>
      <LaunchWindDeltaFrequency>0.02</LaunchWindDeltaFrequency>
      <LaunchUseRandomConditions>0</LaunchUseRandomConditions>
      <LaunchCloudCoverPreset>6</LaunchCloudCoverPreset>
      <LaunchCCLow>1.</LaunchCCLow>
      <LaunchCCHigh>1.</LaunchCCHigh>
      <LaunchThermalPosPreset>1</LaunchThermalPosPreset>
      <LaunchThermalPos>0.</LaunchThermalPos>
      <LaunchMultipleThermals>0</LaunchMultipleThermals>
      <LaunchMaxThermals>3</LaunchMaxThermals>
      <LaunchThermalDia>0.</LaunchThermalDia>
      <LaunchThermalHeight>0.</LaunchThermalHeight>
      <LaunchThermalSpeedPreset>99</LaunchThermalSpeedPreset>
      <LaunchThermalSpeed>0.</LaunchThermalSpeed>
      <LaunchLossPreset>2</LaunchLossPreset>
      <LaunchLossPercent>0.99</LaunchLossPercent>
      <LaunchSiteDia>2000.</LaunchSiteDia>
      <LaunchDriftRangeToLoss>1500.</LaunchDriftRangeToLoss>
      <LaunchPayloadDamagePreset>2</LaunchPayloadDamagePreset>
      <LaunchPayloadDamagePercent>0.98</LaunchPayloadDamagePercent>
      <LaunchEngineMisfirePreset>1</LaunchEngineMisfirePreset>
      <LaunchEngineMisfirePercent>0.</LaunchEngineMisfirePercent>
      <LaunchVariableIgnitionDelay>0</LaunchVariableIgnitionDelay>
      <LaunchVariableIgnitionDelaySec>0.08</LaunchVariableIgnitionDelaySec>
      <LaunchRecDeviceFailurePreset>1</LaunchRecDeviceFailurePreset>
      <LaunchRecDeviceFailurePercent>0.</LaunchRecDeviceFailurePercent>
      <LaunchAriframeFailurePreset>1</LaunchAriframeFailurePreset>
      <LaunchAirframeFailurePercent>0.</LaunchAirframeFailurePercent>
      <LaunchTrackLossPreset>1</LaunchTrackLossPreset>
      <LaunchTeckLossPercent>0.</LaunchTeckLossPercent>
      <SimulationName>[K445-None] </SimulationName>
      <VelocityAtLaunchGuideEnd>11.6566</VelocityAtLaunchGuideEnd>
      <WindStartAltitude>0.</WindStartAltitude>
      <TimeToWindShear>0.</TimeToWindShear>
      <TimeToFreeFlight>0.1825</TimeToFreeFlight>
      <TimeToMaxVelocity>3.41375</TimeToMaxVelocity>
      <TimeToMaxAcceleration>0.05</TimeToMaxAcceleration>
      <SamplesPerSecond>800.</SamplesPerSecond>
      <SimulationType>1</SimulationType>
      <LocationDataServerName>Earth</LocationDataServerName>
      <LocationDataServerDisplayName>Standard earth condistions.</LocationDataServerDisplayName>
      <ExecutionTime>1.422</ExecutionTime>
      <RangeAtLanding>-238.829</RangeAtLanding>
      <VelocityAtLanding>32.5485</VelocityAtLanding>
      <XVelcoityAtLanding>4.47041</XVelcoityAtLanding>
      <YVelocityAtLanding>-32.2401</YVelocityAtLanding>
      <StageSeparationTime>0,0,0</StageSeparationTime>
      <StageEjectTime>-1,-1,1.6e+308</StageEjectTime>
      <TimeToDeployment>0,0,19.6163</TimeToDeployment>
      <DeploymentType>32,32,80</DeploymentType>
      <SamplesPerSecondDescent>1.</SamplesPerSecondDescent>
      <CalculationFlags>1</CalculationFlags>
      <Mass0>7.398</Mass0>
      <CG0>1.62454</CG0>
      <LaterialMOI0>0.845756</LaterialMOI0>
      <RadialMOI0>0.0147939</RadialMOI0>
      <SimulationEvents>
        <SimulationEvent>
          <PartSerialNo>10</PartSerialNo>
          <Type>4</Type>
          <DeployAltitude>0.</DeployAltitude>
          <DeplyTime>0.</DeplyTime>
          <HasDeployed>1</HasDeployed>
          <DeployedAt_Altitude>1771.07</DeployedAt_Altitude>
          <DeployedAt_Velocity>25.8368</DeployedAt_Velocity>
          <DeployedAt_Range>-485.277</DeployedAt_Range>
          <DeployedAt_Time>19.6163</DeployedAt_Time>
          <DeviceID>128</DeviceID>
        </SimulationEvent>
      </SimulationEvents>
      <Stage1Engines>
      </Stage1Engines>
      <Stage2Engines>
      </Stage2Engines>
      <Stage3Engines>
        <EngineSet>
          <EngineCount>1</EngineCount>
          <EngineCode>K445</EngineCode>
          <IgnitionDelay>0.</IgnitionDelay>
          <EngineMfg>Cesaroni</EngineMfg>
          <EngineOverhang>12.7</EngineOverhang>
          <CasingCG>0.</CasingCG>
          <MountSerialNo>9</MountSerialNo>
          <EjectionDelay>-2.</EjectionDelay>
        </EngineSet>
      </Stage3Engines>
    </SimulationResults>
  </SimulationResultsList>
</RockSimDocument>
